// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATtWyf2qSTT-V8THmtzORPKaa7mlgv-w',
    appId: '1:240145924114:web:0fc34d5e3d3f15a49718cb',
    messagingSenderId: '240145924114',
    projectId: 'bookstore-a72bc',
    authDomain: 'bookstore-a72bc.firebaseapp.com',
    storageBucket: 'bookstore-a72bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVt6tYnkSZ_zXXK2eqJuV15zfgTyyNm4',
    appId: '1:240145924114:android:13b80e2bf7638c089718cb',
    messagingSenderId: '240145924114',
    projectId: 'bookstore-a72bc',
    storageBucket: 'bookstore-a72bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOWBCt0eovi-wtRTHEG1AeTiLC1U-KL04',
    appId: '1:240145924114:ios:7e36296c1c65575a9718cb',
    messagingSenderId: '240145924114',
    projectId: 'bookstore-a72bc',
    storageBucket: 'bookstore-a72bc.firebasestorage.app',
    iosClientId: '240145924114-fnqf12k335ul14fd2d1q41msrlsdkvmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOWBCt0eovi-wtRTHEG1AeTiLC1U-KL04',
    appId: '1:240145924114:ios:7e36296c1c65575a9718cb',
    messagingSenderId: '240145924114',
    projectId: 'bookstore-a72bc',
    storageBucket: 'bookstore-a72bc.firebasestorage.app',
    iosClientId: '240145924114-fnqf12k335ul14fd2d1q41msrlsdkvmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBATtWyf2qSTT-V8THmtzORPKaa7mlgv-w',
    appId: '1:240145924114:web:d61fdf3bac8f81fd9718cb',
    messagingSenderId: '240145924114',
    projectId: 'bookstore-a72bc',
    authDomain: 'bookstore-a72bc.firebaseapp.com',
    storageBucket: 'bookstore-a72bc.firebasestorage.app',
  );
}
